# Generated by Django 5.2.17 on 2026-09-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Дата")),
                (
                    "user_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Новых пользователей"
                    ),
                ),
                (
                    "event_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Создано событий"
                    ),
                ),
                (
                    "edited_events",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Изменено событий"
                    ),
                ),
                (
                    "cancelled_events",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Отменено событий"
                    ),
                ),
            ],
            options={
                "verbose_name": "Статистика за день",
                "verbose_name_plural": "Статистика",
                "ordering": ["-date"],
            },
        ),
    ]
