# Generated by Django 5.2.17 on 2026-09-28 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_app", "0002_bot_statistics"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Тема")),
                ("date", models.DateField(verbose_name="Дата")),
                ("time", models.TimeField(verbose_name="Время")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=60, verbose_name="Длительность, мин"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидается"),
                            ("confirmed", "Подтверждена"),
                            ("cancelled", "Отменена"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organized_meetings",
                        to="calendar_app.botuser",
                        verbose_name="Организатор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Встреча",
                "verbose_name_plural": "Встречи",
                "ordering": ["date", "time"],
            },
        ),
        migrations.CreateModel(
            name="MeetingParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидается"),
                            ("confirmed", "Подтверждена"),
                            ("cancelled", "Отменена"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="Ответ",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="calendar_app.meeting",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="calendar_app.botuser",
                    ),
                ),
            ],
            options={
                "verbose_name": "Участник встречи",
                "verbose_name_plural": "Участники встречи",
            },
        ),
        migrations.AddField(
            model_name="meeting",
            name="participants",
            field=models.ManyToManyField(
                related_name="meetings",
                through="calendar_app.MeetingParticipant",
                to="calendar_app.botuser",
                verbose_name="Участники",
            ),
        ),
        migrations.AddConstraint(
            model_name="meetingparticipant",
            constraint=models.UniqueConstraint(
                fields=("meeting", "user"), name="unique_meeting_participant"
            ),
        ),
    ]
