# Generated by Django 5.2.17 on 2026-09-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_app", "0003_meetings"),
    ]

    operations = [
        migrations.AddField(
            model_name="botuser",
            name="events_cancelled",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Отменил событий"
            ),
        ),
        migrations.AddField(
            model_name="botuser",
            name="events_created",
            field=models.PositiveIntegerField(default=0, verbose_name="Создал событий"),
        ),
        migrations.AddField(
            model_name="botuser",
            name="events_edited",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Изменил событий"
            ),
        ),
    ]
