# Generated by Django 5.2.17 on 2026-09-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_app", "0004_user_counters"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="Публичное"),
        ),
    ]
